---
title: 'Final assignment of the Statistical Inference course'
author: "Ivan Tiunov"
date: ''
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\section{Part 1. Central limit theorem}

\subsection{Overview: In a few (2-3) sentences explain what is going to be reported on}

\subsection{Simulations: Include English explanations of the simulations you ran, with the accompanying R code. Your explanations should make clear what the R code accomplishes}

\subsection{Sample Mean versus Theoretical Mean: Include figures with titles. In the figures, highlight the means you are comparing. Include text that explains the figures and what is shown on them, and provides appropriate numbers}

\subsection{Sample Variance versus Theoretical Variance: Include figures (output from R) with titles. Highlight the variances you are comparing. Include text that explains your understanding of the differences of the variances}

\subsection{Distribution: Via figures and text, explain how one can tell the distribution is approximately normal}